### ISSUE TITLE
Changer la typo

### ISSUE THREAD

**Issue by DodeletMP4** [eracom-ID402/Site-CyberPunk-Dorian#2]
Il faudrait changer la typographie de mon site internet svp. Pour ca il faut chercher une typo en rapport avec le cyberpunk!

**Comment by TrySeb** [comment]
Hello Doriane je m'en occupe avec plaisir !!!

**Comment by TrySeb** [comment]
Terminé ✅

**Comment by DodeletMP4** [comment]
Danke @TrySeb
